$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1463991110480.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ce3d60aa459f42b3b322120f5d5183aa",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkFrame",
                "description":"打开 首页详细 在 neibu",
                "linkType":"frame",
                "framesToTargets":[{
                    "framePath":["af4fb09cb96c4959992e5dae1e46b33a"],
                    "target":{
                      "targetType":"page",
                      "url":"首页详细.html",
                      "includeVariables":true}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"7b3442658b3445d2bc465748109302f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "stateStyles":{
              "selected":{
}},
            "location":{
              "x":0,
              "y":890},
            "size":{
              "width":141,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5644d472bb0b45f5aa8db3dc2a1041e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
}},
                "location":{
                  "x":0,
                  "y":890},
                "size":{
                  "width":141,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 首页详细 在 neibu",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["af4fb09cb96c4959992e5dae1e46b33a"],
                          "target":{
                            "targetType":"page",
                            "url":"首页详细.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u0.jpg",
            "selected~":"images/首页/u0_selected.png"}},
{
          "id":"beef5e103b8549f1aa883ba7359e326a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
}},
            "location":{
              "x":141,
              "y":890},
            "size":{
              "width":141,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c62b474af5854fe39ff9543f2aaf9aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
}},
                "location":{
                  "x":141,
                  "y":890},
                "size":{
                  "width":141,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 产品 在 neibu",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["af4fb09cb96c4959992e5dae1e46b33a"],
                          "target":{
                            "targetType":"page",
                            "url":"产品.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u2.jpg",
            "selected~":"images/首页/u2_selected.jpg"}},
{
          "id":"7201e2ad14dc47ffad6b4410e35a1620",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
}},
            "location":{
              "x":420,
              "y":890},
            "size":{
              "width":141,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e054a95a07464aee8bfcc02640804130",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
}},
                "location":{
                  "x":420,
                  "y":890},
                "size":{
                  "width":141,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 我 在 neibu",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["af4fb09cb96c4959992e5dae1e46b33a"],
                          "target":{
                            "targetType":"page",
                            "url":"我.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u4.png",
            "selected~":"images/首页/u4_selected.jpg"}},
{
          "id":"ff02bcb2fb0741a2b991c2d7a5c48532",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
}},
            "location":{
              "x":282,
              "y":890},
            "size":{
              "width":142,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d8a0a8169ef4cda8849ec6bbebc28e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
}},
                "location":{
                  "x":282,
                  "y":890},
                "size":{
                  "width":142,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 资产 在 neibu",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["af4fb09cb96c4959992e5dae1e46b33a"],
                          "target":{
                            "targetType":"page",
                            "url":"资产.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u6.png",
            "selected~":"images/首页/u6_selected.jpg"}},
{
          "id":"af4fb09cb96c4959992e5dae1e46b33a",
          "label":"neibu",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "size":{
              "width":561,
              "height":890}},
          "adaptiveStyles":{
}},
{
          "id":"f6f71aaf8be647c28b9852e446228db4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":884},
            "size":{
              "width":561,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u9_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7b3442658b3445d2bc465748109302f0":{
      "scriptId":"u0"},
    "5644d472bb0b45f5aa8db3dc2a1041e7":{
      "scriptId":"u1"},
    "beef5e103b8549f1aa883ba7359e326a":{
      "scriptId":"u2"},
    "c62b474af5854fe39ff9543f2aaf9aa7":{
      "scriptId":"u3"},
    "7201e2ad14dc47ffad6b4410e35a1620":{
      "scriptId":"u4"},
    "e054a95a07464aee8bfcc02640804130":{
      "scriptId":"u5"},
    "ff02bcb2fb0741a2b991c2d7a5c48532":{
      "scriptId":"u6"},
    "8d8a0a8169ef4cda8849ec6bbebc28e6":{
      "scriptId":"u7"},
    "af4fb09cb96c4959992e5dae1e46b33a":{
      "scriptId":"u8"},
    "f6f71aaf8be647c28b9852e446228db4":{
      "scriptId":"u9"}}});