$axure.loadCurrentPage({
  "url":"首页详细.html",
  "generationDate":new Date(1463991110873.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c0efae429fc842dbb6c7aa4bd7a18e5c",
    "type":"Axure:Page",
    "name":"首页详细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d3829cbb0dc744c3800a5fc4f08eac0a",
          "label":"img1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xB7D7D7D7},
            "location":{
              "x":237,
              "y":252},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b66e916e26c4eea96532dbfbd80cebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xB7D7D7D7},
                "location":{
                  "x":237,
                  "y":252},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/img1_u0.png",
            "selected~":"images/首页详细/img1_u0_selected.png"}},
{
          "id":"b8ac161feee147aeb108b738a31f0775",
          "label":"img4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xB7D7D7D7},
            "location":{
              "x":275,
              "y":252},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3010fb32d28412a898380952ae63a1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xB7D7D7D7},
                "location":{
                  "x":275,
                  "y":252},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/img1_u0.png",
            "selected~":"images/首页详细/img1_u0_selected.png"}},
{
          "id":"6d727c9bb61c4318aa7c284055156c79",
          "label":"img5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xB7D7D7D7},
            "location":{
              "x":287,
              "y":252},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b4a3d3b80bc4153bf14070cedd64f23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xB7D7D7D7},
                "location":{
                  "x":287,
                  "y":252},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/img1_u0.png",
            "selected~":"images/首页详细/img1_u0_selected.png"}},
{
          "id":"a4c19539aa4d46d8913be07124f7fcae",
          "label":"hahha",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":560,
              "height":780}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"eb7fe26f74514eaca8f9058e37cba80d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"788884926d0c4f12a5650413579b064d",
                  "label":"kuangj",
                  "parentDynamicPanel":"a4c19539aa4d46d8913be07124f7fcae",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":560,
                      "height":710}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"ec1bc554d95e470ab194cd8d3e0d9c01",
          "label":"img",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":561,
              "height":280}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1<br> (If state of This 等于 img1)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["ec1bc554d95e470ab194cd8d3e0d9c01"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 img1 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d3829cbb0dc744c3800a5fc4f08eac0a"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 2<br> (Else If state of This 等于 img2)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["ec1bc554d95e470ab194cd8d3e0d9c01"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 不明 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]},
{
                  "description":"用例 3<br> (Else If state of This 等于 img3)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["ec1bc554d95e470ab194cd8d3e0d9c01"],
                      "panelIndex":2}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 不明 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]},
{
                  "description":"用例 4<br> (Else If state of This 等于 img4)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["ec1bc554d95e470ab194cd8d3e0d9c01"],
                      "panelIndex":3}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 img4 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b8ac161feee147aeb108b738a31f0775"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 5<br> (Else If state of This 等于 img5)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["ec1bc554d95e470ab194cd8d3e0d9c01"],
                      "panelIndex":4}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 img5 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6d727c9bb61c4318aa7c284055156c79"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 img to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap repeat every 3000 ms",
                      "panelsToStates":[{
                          "panelPath":["ec1bc554d95e470ab194cd8d3e0d9c01"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"4355bb4bfb3c45599779bfdec39f9fd2",
              "label":"img1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f7d9ca64161c49f1956836ca95e9746c",
                  "label":"",
                  "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":561,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7fbc92a35a9341e1b4c0e5327f10a654",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":561,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页详细/u9.png"}}]},
{
              "id":"ebb9abf9aa8f4d45a1253d92c8c30418",
              "label":"img2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"98f9a8b4649942df8deff6e21780b3e2",
                  "label":"",
                  "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":561,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c4f427d1b6a473faf711a1816b4cb72",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":561,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页详细/u11.png"}}]},
{
              "id":"42c908e1100c4255af0e1fea5e65c1fc",
              "label":"img3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"74b64bc8dceb4b5092ac9ce2927dc545",
                  "label":"",
                  "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":561,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12cbf055ffab4b348a783115b14827c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":561,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页详细/u9.png"}}]},
{
              "id":"e4b14bcc86ce4dcb8ba9b81ba4958801",
              "label":"img4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"75fdfc2bc6cb43188f523eda0c8e6ade",
                  "label":"",
                  "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":561,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aee1a30931bb4ec48c6dc5e364d2501a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":561,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页详细/u11.png"}}]},
{
              "id":"a201b1ba02404189a856ad83e427653e",
              "label":"img5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fe4a67325b044171924dd8b3e934e9d6",
                  "label":"",
                  "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":561,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6db5db115d07413487d93fb7df821c41",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ec1bc554d95e470ab194cd8d3e0d9c01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":561,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页详细/u11.png"}}]}]},
{
          "id":"74c0dcfb2bf146969851da81841715f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":0,
              "y":280},
            "size":{
              "width":561,
              "height":39},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0084477d9c5341999c46f660f8b4788f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":0,
                  "y":280},
                "size":{
                  "width":561,
                  "height":39},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u19.png"}},
{
          "id":"c5c55e938de741939e5cace100fb8110",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":-3,
              "y":319},
            "size":{
              "width":561,
              "height":16},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a407a9533b9419ab285c4be1b189072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":-3,
                  "y":319},
                "size":{
                  "width":561,
                  "height":16},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u21.png"}},
{
          "id":"88cbac0f7b344504b7883156553ddba7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":0,
              "y":345},
            "size":{
              "width":561,
              "height":55},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"637dd43dbf1d45e0b5679bb54bc30ba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":0,
                  "y":345},
                "size":{
                  "width":561,
                  "height":55},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u23.png"}},
{
          "id":"158dca272b1a4c7b96e5626e34927b13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":356},
            "size":{
              "width":42,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b564bab57b5545d39590cfdedb7abfd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":356},
                "size":{
                  "width":42,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u25.png"}},
{
          "id":"9b96623282f7469896cb1b293b4be6b5",
          "label":"licai",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":366},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If state of This 等于 licai2)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["9b96623282f7469896cb1b293b4be6b5"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 licai to 下一步 向上滑动 out 500ms 向上滑动 in 500ms wrap repeat every 1000 ms",
                      "panelsToStates":[{
                          "panelPath":["9b96623282f7469896cb1b293b4be6b5"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":1000,
                            "options":{
                              "animateOut":{
                                "easing":"slideUp",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideUp",
                                "duration":500},
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If state of This 等于 licai3)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["9b96623282f7469896cb1b293b4be6b5"],
                      "panelIndex":2}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 licai to 下一步 向上滑动 out 500ms 向上滑动 in 500ms wrap repeat every 3000 ms",
                      "panelsToStates":[{
                          "panelPath":["9b96623282f7469896cb1b293b4be6b5"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideUp",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideUp",
                                "duration":500},
                              "compress":false}}}]}]},
{
                  "description":"用例 3<br> (Else If state of This 等于 licai4)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["9b96623282f7469896cb1b293b4be6b5"],
                      "panelIndex":3}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 licai to 下一步 向上滑动 out 500ms 向上滑动 in 500ms wrap repeat every 3000 ms",
                      "panelsToStates":[{
                          "panelPath":["9b96623282f7469896cb1b293b4be6b5"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideUp",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideUp",
                                "duration":500},
                              "compress":false}}}]}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1<br> (If state of This 等于 licai1)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["9b96623282f7469896cb1b293b4be6b5"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 licai to 下一步 向上滑动 out 500ms 向上滑动 in 500ms wrap repeat every 3000 ms",
                      "panelsToStates":[{
                          "panelPath":["9b96623282f7469896cb1b293b4be6b5"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideUp",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideUp",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d40c177de5d14f09bac8ed6c9d5eb6c9",
              "label":"licai1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"36f3129bdffd4a10b759db9cbcef3aaf",
                  "label":"",
                  "parentDynamicPanel":"9b96623282f7469896cb1b293b4be6b5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":288,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30df1f98cff34d87acc47778894e8b58",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b96623282f7469896cb1b293b4be6b5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":288,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"c4f95c8d3c6f4749b1cd59342244c80d",
              "label":"licai2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"588e2ecb7ee34eff9ce1a635fcca8725",
                  "label":"",
                  "parentDynamicPanel":"9b96623282f7469896cb1b293b4be6b5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":288,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c6bed7f38de7473aaf60abf4d77f155a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b96623282f7469896cb1b293b4be6b5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":288,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"d412cc9400684211b735816283e0051f",
              "label":"licai3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ef0541ba98e340aba09be78f4b517387",
                  "label":"",
                  "parentDynamicPanel":"9b96623282f7469896cb1b293b4be6b5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":288,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62fc2d0e0a8946699b17c4af672c9572",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b96623282f7469896cb1b293b4be6b5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":288,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"6f6d5353524b435c90a8bf08b48807d4",
              "label":"licai4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9735cb881b0b45a0a752991b23e8b61f",
                  "label":"",
                  "parentDynamicPanel":"9b96623282f7469896cb1b293b4be6b5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":240,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"27f5abfa490e4b9397d028f963c5b5d6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b96623282f7469896cb1b293b4be6b5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":240,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"18aa4e40a1434715b289ee0628823ad5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":550},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页详细/u36_line.png"}},
{
          "id":"235e7861c61642919e67ca1d36cc6bcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":-3,
              "y":530},
            "size":{
              "width":561,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ac7cf2de0a04b48815aed5b740bdfdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":-3,
                  "y":530},
                "size":{
                  "width":561,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u37.png"}},
{
          "id":"645888407ec54e66bf32333729d8bb20",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":550},
            "size":{
              "width":180,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页详细/u39_line.png"}},
{
          "id":"c21dd0adacb44ef1b8ac0f51e77b647e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":399},
            "size":{
              "width":561,
              "height":131},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33912c87775941e395a454e58f7978df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":399},
                "size":{
                  "width":561,
                  "height":131},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u40.png"}},
{
          "id":"df061c926adb472581cf126d2197a493",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":213,
              "y":538},
            "size":{
              "width":36,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ee303791ce405aba0a368b9ff7c3be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":213,
                  "y":538},
                "size":{
                  "width":36,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u42.png"}},
{
          "id":"b9425ee707aa412f8bba23941045fdc7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":550},
            "size":{
              "width":160,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页详细/u44_line.png"}},
{
          "id":"f5ac75e8f1d047cfb476244903669e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF39360,
              "opacity":1},
            "location":{
              "x":256,
              "y":543},
            "size":{
              "width":64,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6917504360f42a69a30123b9a9ec6bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF39360,
                  "opacity":1},
                "location":{
                  "x":256,
                  "y":543},
                "size":{
                  "width":64,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ad827965de5450d8302463deb85d434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":561,
              "height":110},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b09b16ba78749798159ac66fdbf82d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":580},
                "size":{
                  "width":561,
                  "height":110},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u47.png"}},
{
          "id":"b68a4289994e411082140d3d22b115e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":5,
              "y":590},
            "size":{
              "width":6,
              "height":20},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1769e51fb30548d39fb5b155e19c59c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":5,
                  "y":590},
                "size":{
                  "width":6,
                  "height":20},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u49.png"}},
{
          "id":"2f9a041212424165ad6a0641cac89df5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":610},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页详细/u51_line.png"}},
{
          "id":"a1f1897431774ce19368eca21e3f0e4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":592},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01eed74e33934610aacc0fded60ea7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":592},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"add80f2568484f08adee67a9de94274c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":110,
              "y":592},
            "size":{
              "width":45,
              "height":16},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bab74bfdff4d4210998f4e47bbc947ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":110,
                  "y":592},
                "size":{
                  "width":45,
                  "height":16},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u54.png"}},
{
          "id":"7200a5d2d0644c449eed3de8efd75cd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":440,
              "y":592},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdb3fac65be044c68783223eb3af85e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":592},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c52c87ed9007496fb48f8a77d75e693e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":32,
              "y":625},
            "size":{
              "width":118,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eb8b538e60c436ea2969fd7929c9272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":625},
                "size":{
                  "width":118,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bde4f05d43004f73abeef680d06ef8e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":35,
              "y":661},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a9e7ff37a0400daf2924db66ba40b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":661},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"693485f1b7be428db1544df77c62a25a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":632},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd3bb13a2ab740238cf8c0f0a72cdf51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":632},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95588191e3ff482badcda05110046172",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":297,
              "y":658},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c183f47f644fbd866152681118c79e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":297,
                  "y":658},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8000f96e4e554c47b498d4b757480ea0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":429,
              "y":640},
            "size":{
              "width":90,
              "height":32},
            "linePattern":"none",
            "cornerRadiusTopLeft":"29"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e8d9d5c697043c6beb0112cbaa9bd25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":429,
                  "y":640},
                "size":{
                  "width":90,
                  "height":32},
                "linePattern":"none",
                "cornerRadiusTopLeft":"29"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u66.png"}},
{
          "id":"5db648f538ef4fb2bab797dad9dc572e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":710},
            "size":{
              "width":561,
              "height":110},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01eb7c665bb14acfb37bbecb1121e1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":710},
                "size":{
                  "width":561,
                  "height":110},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u47.png"}},
{
          "id":"f08004d0474745938df87db01cd1694d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333399},
            "location":{
              "x":6,
              "y":720},
            "size":{
              "width":6,
              "height":20},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9be454635fe149dabc9c9be8e150ca51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333399},
                "location":{
                  "x":6,
                  "y":720},
                "size":{
                  "width":6,
                  "height":20},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u70.png"}},
{
          "id":"3ef808c953f84a5abef16ea85ed0f3f9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":740},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页详细/u51_line.png"}},
{
          "id":"371ca6b3a285430ab805c9813e0473c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333399,
              "opacity":1},
            "location":{
              "x":22,
              "y":722},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c30f0cba861946389d8faedc3fced804",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":722},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38c020a032b44a44963748a343cb1358",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":440,
              "y":722},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e0b4b9421d64a7ab9c3f78e9d498c8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":722},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58530b05267e43ebb3f967275ddbe000",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":34,
              "y":758},
            "size":{
              "width":87,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43daff19d12c463a9d5cd98fdf42175a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":758},
                "size":{
                  "width":87,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"313fe8c5327c43478266554499972c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":36,
              "y":791},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ccd978e5f5407cb320668368f1cfc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":791},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b7d408581e549e5b05497950c578109",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":762},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9d13644d2884c0abf8158aa84b64a60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":762},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb4ac0a6a6ac4bd9b7d6d190a8771d56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":298,
              "y":788},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a621a6c391740569ee5a43f7da6bbb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":298,
                  "y":788},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfc863f71de04ac9bc3ebeb29eac18e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":430,
              "y":770},
            "size":{
              "width":90,
              "height":32},
            "linePattern":"none",
            "cornerRadiusTopLeft":"29"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2543ba89fdf4f838d0927a0e422d492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":430,
                  "y":770},
                "size":{
                  "width":90,
                  "height":32},
                "linePattern":"none",
                "cornerRadiusTopLeft":"29"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u66.png"}},
{
          "id":"8bdf46a90f0e480a99c3ce6c00d164dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":110,
              "y":748},
            "size":{
              "width":50,
              "height":23},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e7a0a01ecf4a19b2e3690408d67969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":110,
                  "y":748},
                "size":{
                  "width":50,
                  "height":23},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页详细/u87.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d3829cbb0dc744c3800a5fc4f08eac0a":{
      "scriptId":"u0"},
    "0b66e916e26c4eea96532dbfbd80cebc":{
      "scriptId":"u1"},
    "b8ac161feee147aeb108b738a31f0775":{
      "scriptId":"u2"},
    "a3010fb32d28412a898380952ae63a1f":{
      "scriptId":"u3"},
    "6d727c9bb61c4318aa7c284055156c79":{
      "scriptId":"u4"},
    "7b4a3d3b80bc4153bf14070cedd64f23":{
      "scriptId":"u5"},
    "a4c19539aa4d46d8913be07124f7fcae":{
      "scriptId":"u6"},
    "788884926d0c4f12a5650413579b064d":{
      "scriptId":"u7"},
    "ec1bc554d95e470ab194cd8d3e0d9c01":{
      "scriptId":"u8"},
    "f7d9ca64161c49f1956836ca95e9746c":{
      "scriptId":"u9"},
    "7fbc92a35a9341e1b4c0e5327f10a654":{
      "scriptId":"u10"},
    "98f9a8b4649942df8deff6e21780b3e2":{
      "scriptId":"u11"},
    "9c4f427d1b6a473faf711a1816b4cb72":{
      "scriptId":"u12"},
    "74b64bc8dceb4b5092ac9ce2927dc545":{
      "scriptId":"u13"},
    "12cbf055ffab4b348a783115b14827c7":{
      "scriptId":"u14"},
    "75fdfc2bc6cb43188f523eda0c8e6ade":{
      "scriptId":"u15"},
    "aee1a30931bb4ec48c6dc5e364d2501a":{
      "scriptId":"u16"},
    "fe4a67325b044171924dd8b3e934e9d6":{
      "scriptId":"u17"},
    "6db5db115d07413487d93fb7df821c41":{
      "scriptId":"u18"},
    "74c0dcfb2bf146969851da81841715f0":{
      "scriptId":"u19"},
    "0084477d9c5341999c46f660f8b4788f":{
      "scriptId":"u20"},
    "c5c55e938de741939e5cace100fb8110":{
      "scriptId":"u21"},
    "4a407a9533b9419ab285c4be1b189072":{
      "scriptId":"u22"},
    "88cbac0f7b344504b7883156553ddba7":{
      "scriptId":"u23"},
    "637dd43dbf1d45e0b5679bb54bc30ba6":{
      "scriptId":"u24"},
    "158dca272b1a4c7b96e5626e34927b13":{
      "scriptId":"u25"},
    "b564bab57b5545d39590cfdedb7abfd9":{
      "scriptId":"u26"},
    "9b96623282f7469896cb1b293b4be6b5":{
      "scriptId":"u27"},
    "36f3129bdffd4a10b759db9cbcef3aaf":{
      "scriptId":"u28"},
    "30df1f98cff34d87acc47778894e8b58":{
      "scriptId":"u29"},
    "588e2ecb7ee34eff9ce1a635fcca8725":{
      "scriptId":"u30"},
    "c6bed7f38de7473aaf60abf4d77f155a":{
      "scriptId":"u31"},
    "ef0541ba98e340aba09be78f4b517387":{
      "scriptId":"u32"},
    "62fc2d0e0a8946699b17c4af672c9572":{
      "scriptId":"u33"},
    "9735cb881b0b45a0a752991b23e8b61f":{
      "scriptId":"u34"},
    "27f5abfa490e4b9397d028f963c5b5d6":{
      "scriptId":"u35"},
    "18aa4e40a1434715b289ee0628823ad5":{
      "scriptId":"u36"},
    "235e7861c61642919e67ca1d36cc6bcf":{
      "scriptId":"u37"},
    "7ac7cf2de0a04b48815aed5b740bdfdb":{
      "scriptId":"u38"},
    "645888407ec54e66bf32333729d8bb20":{
      "scriptId":"u39"},
    "c21dd0adacb44ef1b8ac0f51e77b647e":{
      "scriptId":"u40"},
    "33912c87775941e395a454e58f7978df":{
      "scriptId":"u41"},
    "df061c926adb472581cf126d2197a493":{
      "scriptId":"u42"},
    "d3ee303791ce405aba0a368b9ff7c3be":{
      "scriptId":"u43"},
    "b9425ee707aa412f8bba23941045fdc7":{
      "scriptId":"u44"},
    "f5ac75e8f1d047cfb476244903669e84":{
      "scriptId":"u45"},
    "f6917504360f42a69a30123b9a9ec6bd":{
      "scriptId":"u46"},
    "6ad827965de5450d8302463deb85d434":{
      "scriptId":"u47"},
    "1b09b16ba78749798159ac66fdbf82d5":{
      "scriptId":"u48"},
    "b68a4289994e411082140d3d22b115e5":{
      "scriptId":"u49"},
    "1769e51fb30548d39fb5b155e19c59c4":{
      "scriptId":"u50"},
    "2f9a041212424165ad6a0641cac89df5":{
      "scriptId":"u51"},
    "a1f1897431774ce19368eca21e3f0e4b":{
      "scriptId":"u52"},
    "01eed74e33934610aacc0fded60ea7d5":{
      "scriptId":"u53"},
    "add80f2568484f08adee67a9de94274c":{
      "scriptId":"u54"},
    "bab74bfdff4d4210998f4e47bbc947ce":{
      "scriptId":"u55"},
    "7200a5d2d0644c449eed3de8efd75cd0":{
      "scriptId":"u56"},
    "bdb3fac65be044c68783223eb3af85e0":{
      "scriptId":"u57"},
    "c52c87ed9007496fb48f8a77d75e693e":{
      "scriptId":"u58"},
    "3eb8b538e60c436ea2969fd7929c9272":{
      "scriptId":"u59"},
    "bde4f05d43004f73abeef680d06ef8e1":{
      "scriptId":"u60"},
    "d5a9e7ff37a0400daf2924db66ba40b0":{
      "scriptId":"u61"},
    "693485f1b7be428db1544df77c62a25a":{
      "scriptId":"u62"},
    "bd3bb13a2ab740238cf8c0f0a72cdf51":{
      "scriptId":"u63"},
    "95588191e3ff482badcda05110046172":{
      "scriptId":"u64"},
    "71c183f47f644fbd866152681118c79e":{
      "scriptId":"u65"},
    "8000f96e4e554c47b498d4b757480ea0":{
      "scriptId":"u66"},
    "6e8d9d5c697043c6beb0112cbaa9bd25":{
      "scriptId":"u67"},
    "5db648f538ef4fb2bab797dad9dc572e":{
      "scriptId":"u68"},
    "01eb7c665bb14acfb37bbecb1121e1df":{
      "scriptId":"u69"},
    "f08004d0474745938df87db01cd1694d":{
      "scriptId":"u70"},
    "9be454635fe149dabc9c9be8e150ca51":{
      "scriptId":"u71"},
    "3ef808c953f84a5abef16ea85ed0f3f9":{
      "scriptId":"u72"},
    "371ca6b3a285430ab805c9813e0473c7":{
      "scriptId":"u73"},
    "c30f0cba861946389d8faedc3fced804":{
      "scriptId":"u74"},
    "38c020a032b44a44963748a343cb1358":{
      "scriptId":"u75"},
    "9e0b4b9421d64a7ab9c3f78e9d498c8e":{
      "scriptId":"u76"},
    "58530b05267e43ebb3f967275ddbe000":{
      "scriptId":"u77"},
    "43daff19d12c463a9d5cd98fdf42175a":{
      "scriptId":"u78"},
    "313fe8c5327c43478266554499972c92":{
      "scriptId":"u79"},
    "85ccd978e5f5407cb320668368f1cfc8":{
      "scriptId":"u80"},
    "5b7d408581e549e5b05497950c578109":{
      "scriptId":"u81"},
    "e9d13644d2884c0abf8158aa84b64a60":{
      "scriptId":"u82"},
    "eb4ac0a6a6ac4bd9b7d6d190a8771d56":{
      "scriptId":"u83"},
    "1a621a6c391740569ee5a43f7da6bbb1":{
      "scriptId":"u84"},
    "bfc863f71de04ac9bc3ebeb29eac18e3":{
      "scriptId":"u85"},
    "a2543ba89fdf4f838d0927a0e422d492":{
      "scriptId":"u86"},
    "8bdf46a90f0e480a99c3ce6c00d164dc":{
      "scriptId":"u87"},
    "a8e7a0a01ecf4a19b2e3690408d67969":{
      "scriptId":"u88"}}});